name: Aubrie
favicon: null
layout_spectrum: 0.6678920139092952
typography_spectrum: 0.56814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7e8983'
    - '#44565a'
    - '#bcc7c3'
    - '#8f5025'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
