name: Aubrie
favicon: null
layout_spectrum: 0.6678920139092952
typography_spectrum: 0.56814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#856a5f'
    - '#111419'
    - '#9d9d9f'
    - '#6777ff'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
